remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Forecasting Power Outage Duration Using Predictive Models"
description: "Predicting the duration of power outages using machine learning"
