remote_theme: just-the-docs/just-the-docs@v0.5.4
plugins:
  - jekyll-remote-theme

title: "Forecasting Power Outage Duration Using Predictive Models"
description: "Predicting the duration of power outages using machine learning"

# Optional: Sidebar navigation settings
just_the_docs:
  logo: "" # You can add a logo path here later
  search_enabled: true
  color_scheme: light
  heading_anchors: true
