remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

nav_enabled: false
search_enabled: false
aux_links:
  View on GitHub:
    - https://github.com/gideonshaked/eecs398-final-project-power-outages
